CREATE TABLE `TBL_USER_EN` (
`USER_SEQ` BIGINT NOT NULL,
`USER_ID` VARCHAR(50) NOT NULL,
`USER_PASS` VARCHAR(256) DEFAULT NULL,
`USER_NAME` VARCHAR(40) DEFAULT NULL,
`USER_EMAIL` VARCHAR(200) DEFAULT NULL,
`REGDATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`USER_SEQ`)
);

CREATE TABLE `TBL_USER_KR` (
`USER_SEQ` BIGINT NOT NULL,
`USER_ID` VARCHAR(50) NOT NULL,
`USER_PASS` VARCHAR(256) DEFAULT NULL,
`USER_NAME` VARCHAR(40) DEFAULT NULL,
`USER_EMAIL` VARCHAR(200) DEFAULT NULL,
`REGDATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`USER_SEQ`)
);

CREATE TABLE `TBL_USER_LOG` (
`USER_LOG_SEQ` BIGINT NOT NULL AUTO_INCREMENT,
`USER_SEQ` BIGINT NOT NULL,
`USER_ID` VARCHAR(50) NOT NULL,
`USER_PASS` VARCHAR(50) DEFAULT NULL,
`USER_NAME` VARCHAR(40) DEFAULT NULL,
`USER_EMAIL` VARCHAR(200) DEFAULT NULL,
`ACTION` char(1) DEFAULT NULL COMMENT 'I : 등록 / U : 수정  / D : 삭제 ',
`REGDATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`USER_LOG_SEQ`)
);


CREATE TABLE `TBL_BOARD` (
`BOARD_SEQ` BIGINT NOT NULL AUTO_INCREMENT,
`USER_SEQ` BIGINT NOT NULL,
`BOARD_TITLE` VARCHAR(200) DEFAULT NULL,
`BOARD_CONTENTS` TEXT DEFAULT NULL,
`REGDATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`BOARD_SEQ`)
);







CREATE TABLE `TBL_COMMENT` (
`COMMENT_SEQ` BIGINT NOT NULL AUTO_INCREMENT,
`BOARD_SEQ` BIGINT NOT NULL,
`USER_SEQ` BIGINT NOT NULL,
`COMMENT_CONTENTS` VARCHAR(280) DEFAULT NULL,
`REGDATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`COMMENT_SEQ`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;

CREATE TABLE `TBL_FOLLOW` (
`FOLLOW_SEQ` BIGINT NOT NULL,
`FOLLOWEE_SEQ` BIGINT NOT NULL,
`REGDATE` DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`FOLLOW_SEQ`)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;

