CREATE TABLE `TBL_SEQUENCE`  (
`SEQUENCE_NAME` VARCHAR(50) NOT NULL,
`CURRENT_VALUE` BIGINT NOT NULL DEFAULT 0,
`INCREMENT` BIGINT NOT NULL DEFAULT 1,
PRIMARY KEY (`SEQUENCE_NAME`)
);

INSERT INTO `TBL_SEQUENCE` VALUES ('userSeq', 0, 1);

DROP FUNCTION IF EXISTS `CURRVAL`;
DELIMITER ;;
CREATE FUNCTION `CURRVAL`(_seqName VARCHAR(50)) RETURNS BIGINT
BEGIN
	DECLARE renVal BIGINT;
	SET renVal = 0;
	
	SELECT CURRENT_VALUE INTO renVal
	FROM TBL_SEQUENCE
	WHERE SEQUENCE_NAME = _seqName;

	RETURN renVal;
END
;;
DELIMITER ;

DROP FUNCTION IF EXISTS `NEXTVAL`;
DELIMITER ;;
CREATE FUNCTION `NEXTVAL`(_seqName VARCHAR(50)) RETURNS BIGINT
BEGIN
	UPDATE TBL_SEQUENCE
	SET CURRENT_VALUE = CURRENT_VALUE + INCREMENT
	WHERE SEQUENCE_NAME = _seqName;

	RETURN CURRVAL(_seqName);
END
;;
DELIMITER ;


DROP FUNCTION IF EXISTS `SETVAL`;
DELIMITER ;;
CREATE FUNCTION `SETVAL`(_seqName VARCHAR(50), _setVal BIGINT) RETURNS BIGINT
BEGIN
	UPDATE TBL_SEQUENCE
	SET CURRENT_VALUE = _setVal
	WHERE SEQUENCE_NAME = _seqName;

	RETURN CURRVAL(_seqName);
END
;;
DELIMITER ;

SELECT CURRVAL('userSeq');
-- SEQUENCE            userSeq      10
SELECT SETVAL('userSeq', 0);
-- SEQUENCE            userSeq
SELECT CURRVAL('userSeq');
-- SEQUENCE            userSeq
SELECT NEXTVAL('userSeq');


SELECT * FROM TBL_SEQUENCE;